name = "sullyos-perspective"
main = "worker.bundle.js"
compatibility_date = "2026-01-01"
keep_vars = true

[observability]
enabled = true

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "sullyos-perspective"
database_id = "b337ddb9-8e4d-4901-a2f1-3d96cc628cca"

[triggers]
crons = ["17 4 * * *"]
